import React from 'react';
import {
  PermissionsAndroid,
  Platform,
  Text,
  TouchableOpacity,
  Alert,
} from 'react-native';
import Share from 'react-native-share';
import RNPrint from 'react-native-print';
import RNFS from 'react-native-fs';
import {useAlert} from '../../Providers/AlertContext';

// PDFTranslations.js or add this to your existing PDFExportComponent
const PDFTranslations = {
  en: {
    // UI Texts
    Export: 'Export',
    'Choose Export Format': 'Choose Export Format',
    'PDF Document': 'PDF Document',
    'Excel Spreadsheet': 'Excel Spreadsheet',
    'Portable Document Format - Great for viewing and printing':
      'Portable Document Format - Great for viewing and printing',
    'Microsoft Excel format - Great for data analysis':
      'Microsoft Excel format - Great for data analysis',
    'Export Failed': 'Export Failed',
    'An error occurred while exporting the file.':
      'An error occurred while exporting the file.',

    // PDF Content
    'Generated on': 'Generated on',
    'No Data Available for Export': 'No Data Available for Export',
    'Try adjusting your filters or check back later.':
      'Try adjusting your filters or check back later.',
    'Total Records': 'Total Records',
    Columns: 'Columns',
    'Export Date': 'Export Date',
    'Generated by BiometricPro': 'Generated by BiometricPro',
    'Generated by BiometricPro Document Management System':
      'Generated by BiometricPro Document Management System',

    // Request Management Columns
    Subject: 'Subject',
    Type: 'Type',
    Status: 'Status',
    'Created Date': 'Created Date',
    Description: 'Description',
    'Request Management Export': 'Request Management Export',
    Name: 'Name',
    'Date - Time': 'Date - Time',

    // Expense Management Columns
    Amount: 'Amount',
    Currency: 'Currency',
    'Expense Date': 'Expense Date',
    'Payment Date': 'Payment Date',
    Note: 'Note',
    'Document Name': 'Document Name',
    Category: 'Category',

    // Document Management Columns
    'File Type': 'File Type',
    'Upload Date': 'Upload Date',
    'Policy Name': 'Policy Name',

    // Worker/Employee Management Columns
    'Worker Name': 'Worker Name',
    'Tasks Assigned': 'Tasks Assigned',
    'Tasks Completed': 'Tasks Completed',
    'Productive Tasks': 'Productive Tasks',
    'Avg Task Time (Hours)': 'Avg Task Time (Hours)',
    'Hours Worked': 'Hours Worked',
    'Compliance %': 'Compliance %',
    'Productivity %': 'Productivity %',
    'Efficiency %': 'Efficiency %',
    'Employee ID': 'Employee ID',
    'Company Name': 'Company Name',

    // Attendance Management Columns
    'Total Scheduled Days': 'Total Scheduled Days',
    'Days Attended': 'Days Attended',
    'Days Absent': 'Days Absent',
    'Total Scheduled Hours': 'Total Scheduled Hours',
    'Total Actual Hours': 'Total Actual Hours',
    'Total Hours Variance': 'Total Hours Variance',
    'Avg Scheduled Hours/Day': 'Avg Scheduled Hours/Day',
    'Avg Actual Hours/Day': 'Avg Actual Hours/Day',
    'Overall Compliance %': 'Overall Compliance %',
    'Attendance Rate %': 'Attendance Rate %',
    'Start Date': 'Start Date',
    'End Date': 'End Date',
    Date: 'Date',

    // Time Tracking Columns
    'Check In': 'Check In',
    'Check Out': 'Check Out',
    'Working Hours': 'Working Hours',
    'Total Punches': 'Total Punches',

    // Task Management Columns
    'Task Title': 'Task Title',
    'Assigned By': 'Assigned By',
    Location: 'Location',

    // Generic/Common Columns
    ID: 'ID',
    Action: 'Action',
    Comments: 'Comments',
    Priority: 'Priority',
    Department: 'Department',
    Position: 'Position',
    Manager: 'Manager',
    Team: 'Team',
    Project: 'Project',
    Deadline: 'Deadline',
    Progress: 'Progress',
    Rating: 'Rating',
    Score: 'Score',
    Level: 'Level',
    Grade: 'Grade',
    Status: 'Status',
    Result: 'Result',
    Outcome: 'Outcome',
    Performance: 'Performance',
  },
  es: {
    // UI Texts
    Export: 'Exportar',
    'Choose Export Format': 'Elegir Formato de Exportación',
    'PDF Document': 'Documento PDF',
    'Excel Spreadsheet': 'Hoja de Cálculo Excel',
    'Portable Document Format - Great for viewing and printing':
      'Formato de Documento Portátil - Ideal para visualizar e imprimir',
    'Microsoft Excel format - Great for data analysis':
      'Formato Microsoft Excel - Ideal para análisis de datos',
    'Export Failed': 'Exportación Fallida',
    'An error occurred while exporting the file.':
      'Ocurrió un error al exportar el archivo.',

    // PDF Content
    'Generated on': 'Generado el',
    'No Data Available for Export': 'No hay datos disponibles para exportar',
    'Try adjusting your filters or check back later.':
      'Intente ajustar sus filtros o verifique más tarde.',
    'Total Records': 'Registros Totales',
    Columns: 'Columnas',
    'Export Date': 'Fecha de Exportación',
    'Generated by BiometricPro': 'Generado por BiometricPro',
    'Generated by BiometricPro Document Management System':
      'Generado por el Sistema de Gestión de Documentos BiometricPro',

    // Request Management Columns
    Subject: 'Asunto',
    Type: 'Tipo',
    Status: 'Estado',
    'Created Date': 'Fecha de Creación',
    Description: 'Descripción',
    'Request Management Export': 'Exportación de Gestión de Solicitudes',
    Name: 'Nombre',
    'Date - Time': 'Fecha - Hora',

    // Expense Management Columns
    Amount: 'Monto',
    Currency: 'Moneda',
    'Expense Date': 'Fecha de Gasto',
    'Payment Date': 'Fecha de Pago',
    Note: 'Nota',
    'Document Name': 'Nombre del Documento',
    Category: 'Categoría',

    // Document Management Columns
    'File Type': 'Tipo de Archivo',
    'Upload Date': 'Fecha de Subida',
    'Policy Name': 'Nombre de la Política',

    // Worker/Employee Management Columns
    'Worker Name': 'Nombre del Trabajador',
    'Tasks Assigned': 'Tareas Asignadas',
    'Tasks Completed': 'Tareas Completadas',
    'Productive Tasks': 'Tareas Productivas',
    'Avg Task Time (Hours)': 'Tiempo Promedio de Tarea (Horas)',
    'Hours Worked': 'Horas Trabajadas',
    'Compliance %': '% de Cumplimiento',
    'Productivity %': '% de Productividad',
    'Efficiency %': '% de Eficiencia',
    'Employee ID': 'ID del Empleado',
    'Company Name': 'Nombre de la Empresa',

    // Attendance Management Columns
    'Total Scheduled Days': 'Días Programados Totales',
    'Days Attended': 'Días Asistidos',
    'Days Absent': 'Días Ausentes',
    'Total Scheduled Hours': 'Horas Programadas Totales',
    'Total Actual Hours': 'Horas Reales Totales',
    'Total Hours Variance': 'Variación de Horas Totales',
    'Avg Scheduled Hours/Day': 'Horas Programadas Promedio/Día',
    'Avg Actual Hours/Day': 'Horas Reales Promedio/Día',
    'Overall Compliance %': '% de Cumplimiento General',
    'Attendance Rate %': '% de Asistencia',
    'Start Date': 'Fecha de Inicio',
    'End Date': 'Fecha de Fin',
    Date: 'Fecha',

    // Time Tracking Columns
    'Check In': 'Registro de Entrada',
    'Check Out': 'Registro de Salida',
    'Working Hours': 'Horas de Trabajo',
    'Total Punches': 'Total de Registros',

    // Task Management Columns
    'Task Title': 'Título de la Tarea',
    'Assigned By': 'Asignado Por',
    Location: 'Ubicación',

    // Generic/Common Columns
    ID: 'ID',
    Action: 'Acción',
    Comments: 'Comentarios',
    Priority: 'Prioridad',
    Department: 'Departamento',
    Position: 'Posición',
    Manager: 'Gerente',
    Team: 'Equipo',
    Project: 'Proyecto',
    Deadline: 'Fecha Límite',
    Progress: 'Progreso',
    Rating: 'Calificación',
    Score: 'Puntuación',
    Level: 'Nivel',
    Grade: 'Grado',
    Status: 'Estado',
    Result: 'Resultado',
    Outcome: 'Resultado Final',
    Performance: 'Rendimiento',
  },
};

class PDFExportComponent {
  constructor(props) {
    this.props = props;
    this.currentLanguage = props.currentLanguage || 'en';
    this.translations =
      PDFTranslations[this.currentLanguage] || PDFTranslations.en;
    this.companyLogo = props.companyLogo || null; // Make sure this is properly set
    this.showAlert = props.showAlert || null;
    this.documentType = props.documentType || null;
    this.documentData = props.documentData || null;

    console.log('📄 PDFExportComponent initialized:', {
      currentLanguage: this.currentLanguage,
      companyLogo: this.companyLogo,
      hasCompanyLogo: !!this.companyLogo,
      documentType: this.documentType,
      hasDocumentData: !!this.documentData,
    });
  }

  // Helper method to convert image URL to base64
  urlToBase64 = async imageUrl => {
    try {
      if (!imageUrl) {
        console.log('❌ No image URL provided');
        return null;
      }

      const fileName = imageUrl.split('/').pop();
      const localPath = `${RNFS.CachesDirectoryPath}/${fileName}`;

      console.log('📥 Downloading image:', imageUrl);

      // Download image locally
      const dl = RNFS.downloadFile({
        fromUrl: imageUrl,
        toFile: localPath,
      });
      const result = await dl.promise;

      // Check download status and file existence before reading
      if (!result || (result.statusCode && result.statusCode >= 400)) {
        console.log(
          '❌ Image download failed or returned non-2xx status:',
          result,
        );
        return null;
      }

      const exists = await RNFS.exists(localPath);
      if (!exists) {
        console.log(
          '❌ Download completed but file does not exist at path:',
          localPath,
        );
        return null;
      }

      // Convert to base64
      const base64 = await RNFS.readFile(localPath, 'base64');
      console.log('✅ Image converted to base64, length:', base64.length);

      return base64;
    } catch (error) {
      console.log('❌ Image Base64 Error:', error);
      return null;
    }
  };

  // Helper method to get translated text
  t = key => {
    return this.translations[key] || key;
  };

  // Helper method to format date according to language
  formatDateForLanguage = dateString => {
    if (!dateString) return '-';

    try {
      const date = new Date(dateString);
      if (isNaN(date.getTime())) return '-';

      const options = {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      };

      // Add time options for detailed dates
      if (dateString.includes(':')) {
        options.hour = '2-digit';
        options.minute = '2-digit';
      }

      return date.toLocaleDateString(
        this.currentLanguage === 'es' ? 'es-ES' : 'en-US',
        options,
      );
    } catch (error) {
      return '-';
    }
  };

  requestStoragePermission = async () => {
    if (Platform.OS === 'android') {
      try {
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
          {
            title:
              this.currentLanguage === 'es'
                ? 'Permiso de Almacenamiento Requerido'
                : 'Storage Permission Required',
            message:
              this.currentLanguage === 'es'
                ? 'Esta aplicación necesita acceso a su almacenamiento para guardar archivos PDF'
                : 'This app needs access to your storage to save PDF files',
            buttonPositive: 'OK',
          },
        );
        return granted === PermissionsAndroid.RESULTS.GRANTED;
      } catch (err) {
        console.warn(err);
        return false;
      }
    }
    return true;
  };

  processColumns = columns => {
    const processedColumns = columns.slice(0, this.props.maxColumns);

    // Translate column labels
    return processedColumns.map(column => ({
      ...column,
      label: this.t(column.label), // Translate the column label
    }));
  };

  formatCellData = (data, key) => {
    if (!data) return '-';

    if (key.includes('date') || key.includes('Date')) {
      return this.formatDateForLanguage(data);
    }

    if (key === 'file_type') {
      return String(data).toUpperCase();
    }

    if (key === 'status') {
      const status = String(data);
      // Translate common status values
      const statusTranslations = {
        APPROVED: this.currentLanguage === 'es' ? 'Aprobado' : 'Approved',
        REJECTED: this.currentLanguage === 'es' ? 'Rechazado' : 'Rejected',
        PENDING: this.currentLanguage === 'es' ? 'Pendiente' : 'Pending',
        CANCELLED: this.currentLanguage === 'es' ? 'Cancelado' : 'Cancelled',
        INFO_REQUESTED:
          this.currentLanguage === 'es'
            ? 'Información Solicitada'
            : 'Info Requested',
      };

      return (
        statusTranslations[status] ||
        status.charAt(0).toUpperCase() + status.slice(1).toLowerCase()
      );
    }

    return String(data) || '-';
  };

  generateHTML = async () => {
    const {
      data = [],
      columns = [],
      title = 'Export',
      maxColumns = 5,
      documentType = null, // 'employment_certificate', 'payslip', or null for table
      documentData = null, // Custom data for documents
    } = this.props;

    const processedColumns = this.processColumns(columns);
    const translatedTitle = this.t(title);

    // Generate custom document templates if documentType is specified
    if (documentType && documentData) {
      return this.generateDocumentHTML(
        documentType,
        documentData,
        translatedTitle,
      );
    }

    // Convert company logo to base64 if provided
    let logoTag = '';
    if (this.companyLogo) {
      const base64Logo = await this.urlToBase64(this.companyLogo);
      if (base64Logo) {
        logoTag = `<img src="data:image/png;base64,${base64Logo}" class="company-logo" />`;
        console.log('✅ Logo added to PDF');
      } else {
        console.log('❌ Failed to process logo');
      }
    } else {
      console.log('ℹ️ No company logo provided');
    }

    if (!data || data.length === 0) {
      const currentDate = new Date();
      const formattedDate = currentDate.toLocaleDateString(
        this.currentLanguage === 'es' ? 'es-ES' : 'en-US',
        {
          weekday: 'long',
          year: 'numeric',
          month: 'long',
          day: 'numeric',
        },
      );

      return `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <style>
            body { 
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
              margin: 20px;
              color: #333;
              line-height: 1.6;
              background-color: #f8f9fa;
            }
            .container {
              background-color: white;
              padding: 40px;
              border-radius: 12px;
              box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            }
            .header { 
              text-align: center; 
              margin-bottom: 40px;
              border-bottom: 3px solid #007AFF;
              padding-bottom: 25px;
              position: relative;
            }
            .logo-container {
              position: absolute;
              left: 0;
              top: 0;
            }
            .company-logo {
              height: 60px;
              width: auto;
              max-width: 150px;
              object-fit: contain;
            }
            .title { 
              font-size: 24px; 
              font-weight: bold; 
              color: #003149;
              margin-bottom: 10px;
              letter-spacing: -0.5px;
            }
            .no-data { 
              text-align: center; 
              font-size: 18px; 
              color: #666;
              margin-top: 80px;
              padding: 60px 40px;
              background-color: #f8f9fa;
              border-radius: 12px;
              border: 2px dashed #ddd;
            }
            .date {
              font-size: 14px;
              color: #666;
              font-weight: 500;
            }
            .watermark {
              position: fixed;
              bottom: 20px;
              right: 20px;
              font-size: 10px;
              color: #ccc;
              opacity: 0.7;
            }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <div class="logo-container">
                ${logoTag}
              </div>
              <div class="title">${translatedTitle}</div>
            
            <div class="no-data">
              📄 ${this.t('No Data Available for Export')}
              <br><br>
              <span style="font-size: 14px; color: #888;">
                ${this.t('Try adjusting your filters or check back later.')}
              </span>
            </div>
          </div>
        </body>
        </html>
      `;
    }

    const columnWidth = Math.floor(100 / processedColumns.length);

    const tableHeaders = processedColumns
      .map(
        (column, index) => `
        <th style="
          border: 1px solid #e1e5e9;
          padding: 16px 12px;
          background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
          text-align: left;
          font-weight: 700;
          color: #495057;
          font-size: 14px;
          width: ${columnWidth}%;
          position: sticky;
          top: 0;
          ${index === 0 ? 'border-top-left-radius: 8px;' : ''}
          ${
            index === processedColumns.length - 1
              ? 'border-top-right-radius: 8px;'
              : ''
          }
        ">${column.label}</th>
      `,
      )
      .join('');

    const tableRows = data
      .map(
        (row, rowIndex) => `
        <tr style="
          ${
            rowIndex % 2 === 0
              ? 'background-color: #ffffff;'
              : 'background-color: #f8f9fa;'
          }
          transition: background-color 0.2s ease;
        ">
          ${processedColumns
            .map(
              (column, colIndex) => `
            <td style="
              border: 1px solid #e1e5e9;
              padding: 14px 12px;
              font-size: 13px;
              color: #495057;
              line-height: 1.5;
              word-wrap: break-word;
              max-width: 0;
              overflow: hidden;
              text-overflow: ellipsis;
              width: ${columnWidth}%;
            ">${this.formatCellData(row[column.key], column.key)}</td>
          `,
            )
            .join('')}
        </tr>
      `,
      )
      .join('');

    const currentDate = new Date();
    const formattedDate = currentDate.toLocaleDateString(
      this.currentLanguage === 'es' ? 'es-ES' : 'en-US',
      {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      },
    );

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          body { 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            margin: 0;
            padding: 20px;
            color: #333;
            line-height: 1.6;
            background-color: #f8f9fa;
          }
          .container {
            background-color: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            max-width: 1200px;
            margin: 0 auto;
          }
          .header { 
            text-align: center; 
            margin-bottom: 35px;
            border-bottom: 3px solid #007AFF;
            padding-bottom: 25px;
            position: relative;
          }
          .logo-container {
            position: absolute;
            left: 0;
            top: 0;
          }
          .company-logo {
            height: 60px;
            width: auto;
            max-width: 150px;
            object-fit: contain;
          }
          .title { 
            font-size: 32px; 
            font-weight: bold; 
            color: #003149;
            margin-bottom: 10px;
            letter-spacing: -0.5px;
          }
          .date {
            font-size: 14px;
            color: #666;
            font-weight: 500;
          }
          .table-container {
            overflow-x: auto;
            margin: 20px 0;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
            background-color: white;
          }
          th {
            border: 1px solid #e1e5e9;
            padding: 16px 12px;
            background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
            text-align: left;
            font-weight: 700;
            color: #495057;
            position: sticky;
            top: 0;
            z-index: 10;
          }
          td {
            border: 1px solid #e1e5e9;
            padding: 14px 12px;
            color: #495057;
            word-wrap: break-word;
            max-width: 200px;
          }
          tr:nth-child(even) {
            background-color: #f8f9fa;
          }
          tr:hover {
            background-color: #e3f2fd;
          }
          .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 2px solid #e9ecef;
            padding-top: 20px;
            background: linear-gradient(135deg, #f8f9fa 0%, #ffffff 100%);
            border-radius: 8px;
            padding: 20px;
          }
          .stats {
            display: flex;
            justify-content: space-around;
            margin-bottom: 15px;
            flex-wrap: wrap;
            direction: ${this.currentLanguage === 'es' ? 'rtl' : 'ltr'};
          }
          .stat-item {
            text-align: center;
            margin: 5px;
          }
          .stat-number {
            font-size: 18px;
            font-weight: bold;
            color: #007AFF;
          }
          .stat-label {
            font-size: 11px;
            color: #666;
            margin-top: 2px;
          }
          @media print {
            body { 
              margin: 0; 
              background-color: white;
            }
            .container {
              box-shadow: none;
              border-radius: 0;
            }
            .header { page-break-inside: avoid; }
            table { page-break-inside: auto; }
            tr { page-break-inside: avoid; page-break-after: auto; }
            th { page-break-after: avoid; }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <div class="logo-container">
              ${logoTag}
            </div>
            <div class="title">${translatedTitle}</div>
          
          </div>
          
          <div class="table-container">
            <table>
              <thead>
                <tr>${tableHeaders}</tr>
              </thead>
              <tbody>${tableRows}</tbody>
            </table>
          </div>
          
          </div>
        </div>
      </body>
      </html>
    `;
  };

  generateDocumentHTML = (documentType, documentData, title) => {
    if (documentType === 'employment_certificate') {
      return this.generateEmploymentCertificateHTML(documentData, title);
    } else if (documentType === 'payslip') {
      return this.generatePayslipHTML(documentData, title);
    }

    // Fallback to empty data if no matching document type
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 20px;
            color: #333;
          }
          .container {
            padding: 40px;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>${title}</h1>
          <p>Document type not supported: ${documentType}</p>
        </div>
      </body>
      </html>
    `;
  };

  generateEmploymentCertificateHTML = (data, title) => {
    const formatDate = dateString => {
      if (!dateString) return '-';
      try {
        const date = new Date(dateString);
        return date.toLocaleDateString(
          this.currentLanguage === 'es' ? 'es-ES' : 'en-US',
          {year: 'numeric', month: 'long', day: 'numeric'},
        );
      } catch {
        return '-';
      }
    };

    const logoHtml = data.companyLogo
      ? `<img src="data:image/png;base64,${data.companyLogo}" class="company-logo" />`
      : '';

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 40px;
            line-height: 1.6;
            color: #333;
          }
          .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 3px solid #007AFF;
            padding-bottom: 30px;
          }
          .company-logo {
            max-width: 150px;
            margin-bottom: 20px;
          }
          .title {
            font-size: 28px;
            font-weight: bold;
            margin-bottom: 30px;
            color: #003149;
          }
          .content {
            margin-bottom: 30px;
            font-size: 14px;
          }
          .field {
            margin-bottom: 15px;
            display: flex;
          }
          .field-label {
            font-weight: bold;
            min-width: 200px;
          }
          .field-value {
            flex: 1;
          }
          .signature {
            margin-top: 60px;
            text-align: right;
          }
          .signature-line {
            margin-top: 40px;
            margin-bottom: 10px;
          }
          .footer {
            margin-top: 60px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 2px solid #e9ecef;
            padding-top: 20px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          ${logoHtml}
          <h1>${data.companyName || ''}</h1>
          <p>${data.companyAddress || ''}</p>
        </div>

        <div class="title">${title}</div>

        <div class="content">
          <p>This is to certify that <strong>${
            data.workerName || ''
          }</strong> (Employee ID: ${data.workerId || ''}) is/was employed at ${
      data.companyName || ''
    }.</p>

          <div class="field">
            <span class="field-label">Department:</span>
            <span class="field-value">${data.department || '-'}</span>
          </div>

          <div class="field">
            <span class="field-label">Position:</span>
            <span class="field-value">${data.position || '-'}</span>
          </div>

          <div class="field">
            <span class="field-label">Date of Joining:</span>
            <span class="field-value">${formatDate(data.dateOfJoining)}</span>
          </div>

          ${
            data.employmentEndDate
              ? `
          <div class="field">
            <span class="field-label">Employment End Date:</span>
            <span class="field-value">${formatDate(
              data.employmentEndDate,
            )}</span>
          </div>
          `
              : ''
          }

          ${
            data.employmentStatus
              ? `
          <div class="field">
            <span class="field-label">Employment Status:</span>
            <span class="field-value">${data.employmentStatus}</span>
          </div>
          `
              : ''
          }

          ${
            data.workSchedule
              ? `
          <div class="field">
            <span class="field-label">Work Schedule:</span>
            <span class="field-value">${data.workSchedule}</span>
          </div>
          `
              : ''
          }

          ${
            data.salary
              ? `
          <div class="field">
            <span class="field-label">Salary:</span>
            <span class="field-value">${data.currency || ''} ${
                  data.salary
                }</span>
          </div>
          `
              : ''
          }

          <div class="field">
            <span class="field-label">Issue Date:</span>
            <span class="field-value">${formatDate(
              data.issueDate || data.dateOfJoining,
            )}</span>
          </div>
        </div>

        <div class="signature">
          <div class="signature-line">__________________________</div>
          <div><strong>${data.authorizedSignatory || ''}</strong></div>
          <div>${data.companyContact || ''}</div>
        </div>

        <div class="footer">
          <p>${data.companyName || ''} | ${data.companyEmail || ''} | ${
      data.companyPhone || ''
    }</p>
        </div>
      </body>
      </html>
    `;
  };

  generatePayslipHTML = (data, title) => {
    const formatDate = dateString => {
      if (!dateString) return '-';
      try {
        const date = new Date(dateString);
        return date.toLocaleDateString(
          this.currentLanguage === 'es' ? 'es-ES' : 'en-US',
          {year: 'numeric', month: 'long', day: 'numeric'},
        );
      } catch {
        return '-';
      }
    };

    const logoHtml = data.companyLogo
      ? `<img src="data:image/png;base64,${data.companyLogo}" class="company-logo" />`
      : '';

    // Process allowances and deductions
    const allowancesRows = (data.allowancesRows || [])
      .map(
        item => `
      <tr>
        <td>${item.name || ''}</td>
        <td class="amount">${data.currency || ''} ${item.amount || ''}</td>
      </tr>
    `,
      )
      .join('');

    const deductionsRows = (data.deductionsRows || [])
      .map(
        item => `
      <tr>
        <td>${item.name || ''}</td>
        <td class="amount">${data.currency || ''} ${item.amount || ''}</td>
      </tr>
    `,
      )
      .join('');

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 40px;
            line-height: 1.6;
            color: #333;
          }
          .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 3px solid #007AFF;
            padding-bottom: 30px;
          }
          .company-logo {
            max-width: 150px;
            margin-bottom: 20px;
          }
          .title {
            font-size: 28px;
            font-weight: bold;
            margin-bottom: 30px;
            color: #003149;
          }
          .info-section {
            margin-bottom: 30px;
          }
          .info-grid {
            display: table;
            width: 100%;
          }
          .info-row {
            display: table-row;
          }
          .info-cell {
            display: table-cell;
            padding: 8px;
            width: 50%;
          }
          .field-label {
            font-weight: bold;
          }
          .earnings-table, .deductions-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
          }
          .earnings-table th, .earnings-table td,
          .deductions-table th, .deductions-table td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
          }
          .earnings-table th, .deductions-table th {
            background-color: #f5f5f5;
            font-weight: bold;
          }
          .amount {
            text-align: right;
          }
          .total-row {
            font-weight: bold;
            background-color: #f0f0f0;
          }
          .net-pay {
            font-size: 20px;
            font-weight: bold;
            text-align: center;
            margin: 30px 0;
            padding: 15px;
            background-color: #e8f5e9;
            border: 2px solid #4caf50;
          }
          .footer {
            margin-top: 60px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 2px solid #e9ecef;
            padding-top: 20px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          ${logoHtml}
          <h1>${data.companyName || ''}</h1>
          <p>${data.companyAddress || ''}</p>
        </div>

        <div class="title">${title}</div>

        <div class="info-section">
          <div class="info-grid">
            <div class="info-row">
              <div class="info-cell">
                <span class="field-label">Employee Name:</span> ${
                  data.workerName || ''
                }
              </div>
              <div class="info-cell">
                <span class="field-label">Employee ID:</span> ${
                  data.workerId || ''
                }
              </div>
            </div>
            <div class="info-row">
              <div class="info-cell">
                <span class="field-label">Department:</span> ${
                  data.department || ''
                }
              </div>
              <div class="info-cell">
                <span class="field-label">Position:</span> ${
                  data.position || ''
                }
              </div>
            </div>
            <div class="info-row">
              <div class="info-cell">
                <span class="field-label">Period:</span> ${data.period || ''}
              </div>
              <div class="info-cell">
                <span class="field-label">Payment Date:</span> ${formatDate(
                  data.paymentDate,
                )}
              </div>
            </div>
          </div>
        </div>

        <div class="info-section">
          <h3>EARNINGS</h3>
          <table class="earnings-table">
            <thead>
              <tr>
                <th>Description</th>
                <th class="amount">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${allowancesRows}
              <tr>
                <td>Basic Salary</td>
                <td class="amount">${data.currency || ''} ${
      data.basicSalary || ''
    }</td>
              </tr>
              <tr class="total-row">
                <td>TOTAL EARNINGS</td>
                <td class="amount">${data.currency || ''} ${
      data.totalEarnings || ''
    }</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="info-section">
          <h3>DEDUCTIONS</h3>
          <table class="deductions-table">
            <thead>
              <tr>
                <th>Description</th>
                <th class="amount">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${deductionsRows}
              <tr class="total-row">
                <td>TOTAL DEDUCTIONS</td>
                <td class="amount">${data.currency || ''} ${
      data.totalDeductions || ''
    }</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="net-pay">
          NET PAY: ${data.currency || ''} ${data.netPay || ''}
        </div>

        <div class="info-section">
          <div class="info-grid">
            ${
              data.paymentMethod
                ? `
            <div class="info-row">
              <div class="info-cell">
                <span class="field-label">Payment Method:</span> ${
                  data.paymentMethod
                }
              </div>
              ${
                data.bankAccount
                  ? `
              <div class="info-cell">
                <span class="field-label">Bank Account:</span> ${data.bankAccount}
              </div>
              `
                  : ''
              }
            </div>
            `
                : ''
            }
            <div class="info-row">
              <div class="info-cell">
                <span class="field-label">Generated Date:</span> ${formatDate(
                  data.generatedDate,
                )}
              </div>
            </div>
          </div>
        </div>

        <div class="footer">
          <p>${data.companyName || ''} | ${data.companyEmail || ''} | ${
      data.companyPhone || ''
    }</p>
        </div>
      </body>
      </html>
    `;
  };

  handleExportPDF = async () => {
    const {
      onExportStart,
      onExportSuccess,
      onExportError,
      fileName = 'export',
      title = 'Export',
      showShareDialog = true,
    } = this.props;

    try {
      onExportStart?.();

      if (!RNPrint) {
        throw new Error(
          this.currentLanguage === 'es'
            ? 'Biblioteca PDF no disponible. Por favor, instale react-native-print'
            : 'PDF library not available. Please install react-native-print',
        );
      }

      const hasPermission = await this.requestStoragePermission();
      if (!hasPermission) {
        Alert.alert(
          this.currentLanguage === 'es'
            ? 'Permiso Denegado'
            : 'Permission Denied',
          this.currentLanguage === 'es'
            ? 'Se requiere permiso de almacenamiento para exportar archivos PDF'
            : 'Storage permission is required to export PDF files',
        );
        return;
      }

      const html = await this.generateHTML(); // Make this async

      const options = {
        html: html,
        fileName: `${fileName}_${Date.now()}`,
        directory: Platform.OS === 'android' ? 'Downloads' : 'Documents',
      };

      const filePath = await RNPrint.print(options);
      // RNPrint.print may return a string file path or an object depending on platform/version
      const normalizedPath =
        typeof filePath === 'string'
          ? filePath
          : filePath && filePath.filePath
          ? filePath.filePath
          : null;

      if (!normalizedPath) {
        throw new Error(
          this.currentLanguage === 'es'
            ? 'La generación de PDF falló'
            : 'PDF generation failed',
        );
      }

      onExportSuccess?.(normalizedPath);

      // Always show a confirmation alert when PDF is saved successfully
      try {
        this.showAlert?.(
          this.currentLanguage === 'en'
            ? `PDF exportado exitosamente!\n\nArchivo guardado en: ${normalizedPath}`
            : `PDF exported successfully!\n\nFile saved at: ${normalizedPath}`,
          'success',
          'Success',
        );
      } catch (e) {
        // ignore alert errors
      }

      try {
        if (showShareDialog) {
          await Share.open({
            url: normalizedPath.startsWith('file://')
              ? normalizedPath
              : `file://${normalizedPath}`,
            type: 'application/pdf',
            filename: `${fileName}.pdf`,
            subject: this.t(title),
          });
        }
      } catch (shareErr) {
        console.warn('PDF share/open failed:', shareErr);
        // Don't treat share errors as fatal for export success
      }
    } catch (error) {
      console.error('PDF Export Error:', error);
      onExportError?.(error);

      if (
        error.message.includes('PDF library not available') ||
        error.message.includes('Biblioteca PDF no disponible')
      ) {
        Alert.alert(
          this.currentLanguage === 'es'
            ? 'Biblioteca Faltante'
            : 'Library Missing',
          this.currentLanguage === 'es'
            ? 'La funcionalidad de exportación PDF no está disponible. Por favor, instale la biblioteca react-native-print.'
            : 'PDF export functionality is not available. Please install react-native-print library.',
        );
      } else if (error.message.includes('permission')) {
        Alert.alert(
          this.currentLanguage === 'es'
            ? 'Error de Permiso'
            : 'Permission Error',
          this.currentLanguage === 'es'
            ? 'Por favor, conceda permiso de almacenamiento para exportar archivos PDF'
            : 'Please grant storage permission to export PDF files',
        );
      } else {
        // Generic error handling
        Alert.alert(
          this.t('Export Failed'),
          this.t('An error occurred while exporting the file.'),
        );
      }
    }
  };
}

const PDFExportComponentWrapper = ({
  data = [],
  columns = [],
  fileName = 'export',
  title = 'Export',
  buttonTitle = 'Download as PDF',
  buttonStyle,
  textStyle,
  onExportStart,
  onExportSuccess,
  onExportError,
  children,
  showShareDialog = true,
  maxColumns = 5,
  currentLanguage = 'en',
  companyLogo = null, // Add companyLogo prop
  documentType = null,
  documentData = null,
}) => {
  const {showAlert} = useAlert();

  const pdfExporter = new PDFExportComponent({
    data,
    columns,
    fileName,
    title,
    onExportStart,
    onExportSuccess,
    onExportError,
    showShareDialog,
    maxColumns,
    currentLanguage,
    companyLogo,
    documentType,
    documentData,
    showAlert, // Pass showAlert to the component
  });

  // Translate button title based on language
  const translatedButtonTitle =
    currentLanguage === 'es' ? 'Descargar como PDF' : buttonTitle;

  if (children) {
    return React.cloneElement(React.Children.only(children), {
      onPress: pdfExporter.handleExportPDF,
    });
  }

  return (
    <TouchableOpacity
      style={[
        {
          backgroundColor: '#007AFF',
          paddingHorizontal: 20,
          paddingVertical: 12,
          borderRadius: 8,
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: 44,
          shadowColor: '#000',
          shadowOffset: {width: 0, height: 2},
          shadowOpacity: 0.1,
          shadowRadius: 4,
          elevation: 3,
        },
        buttonStyle,
      ]}
      onPress={pdfExporter.handleExportPDF}>
      <Text
        style={[
          {
            color: 'white',
            fontSize: 16,
            fontWeight: '600',
          },
          textStyle,
        ]}>
        {translatedButtonTitle}
      </Text>
    </TouchableOpacity>
  );
};

export default PDFExportComponentWrapper;
export {PDFExportComponent, PDFTranslations};
